apiVersion: v1
kind: ConfigMap
metadata:
  name: smtp-configmap
data:
  smtp_service_name: "{{ .Values.smtp.service_name}}"
  smtp_rabbitmq_service_port: "{{ .Values.smtp.service_port}}"
  recipients: '{{ join "," .Values.smtp.recipients }}'