# Egyenlőre csak az image build a fontos -> a részletek és a helm chart további elemei majd implementációkor
env:
  #A két image egyszerre készül -> elég egy APP_VERSION (ha mégis kell több, akkor majd átírjuk)
  APP_VERSION: 1ff8d65426633147ffc9c844823e91b27a109eb5
rabbitmq:
  username: default_user_waFUPHY_m019tVF5FlC 
  password: J5RSzqB3jpZzIFtuFhenV7Nabw3Sb3g6
  consumer_queue: recognition-request
  publisher_queue: recognition-successful
