# Egyenlőre csak az image build a fontos -> a részletek és a helm chart további elemei majd implementációkor
env:
  #A két image egyszerre készül -> elég egy APP_VERSION (ha mégis kell több, akkor majd átírjuk)
  APP_VERSION: 628bbc0c8ae8e83ef8b2ff1af135c21ccecd267f
  worker_image_name: ocr-worker
  worker_image_tag: dd72f1118373bdbd949002123e7f41a9b6fd55b5
rabbitmq:
  username: default_user_waFUPHY_m019tVF5FlC 
  password: J5RSzqB3jpZzIFtuFhenV7Nabw3Sb3g6
  consumer_queue: recognition-request
  publisher_exchange: ocr_successful_exchange
