#egyenlőre az image tagolása a lényeg -> a helm chart további részét majd kitöltjük a fejlesztéskor
env:
  #APP_VERSION egy string, amely a docker image tag-et fogja tartalmazni. A commit sha-t fogjuk erre használni.
  APP_VERSION: 017625c4dcfd7d63eaf943e86b792860c8c34020