apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-webservice
spec:
  selector:
    matchLabels:
      app: ocr-webservice
  template:
    metadata:
      labels:
        app: ocr-webservice
    spec:
      containers:
        - name: ocr-webservice
          image: vitezalexandra/ocr-webservice:{{ .Values.env.APP_VERSION }}
          env:
            - name: MinioAddr
              valueFrom:
                congigMapKeyRef:
                  name: minio-configmap
                  key: minio_service_name
            - name: MinioPort
              valueFrom:
                congigMapKeyRef:
                  name: minio-configmap
                  key: minio_service_port
            - name: MinioBucket
              valueFrom:
                congigMapKeyRef:
                  name: minio-configmap
                  key: minio_bucket_name
            - name: MinioUser
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: username:
            - name: MinioPassword
              valueFrom:
                secretKeyRef:
                  name: minio-configmap
                  key: password
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
                path: /healthz
                port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
                path: /healthz
                port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3