#RabbitMQ felhasználónév és jelszó
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
data:
  username: "{{.Values.rabbitmq.username | b64enc}}"
  password: "{{.Values.rabbitmq.password | b64enc}}"