#egyenlőre az image tagolása a lényeg -> a helm chart további részét majd kitöltjük a fejlesztéskor
env:
  #APP_VERSION egy string, amely a docker image tag-et fogja tartalmazni. A commit sha-t fogjuk erre használni.
  APP_VERSION: 2dff573feffe441e295ecb0f87eb59d66a146382
#Minden, amit a webservice felhasznál a minio eléréséhez, itt van definiálva
minio:
  service_name: minio.minio.svc.cluster.local
  service_port: 9000
  bucket_name: ocr-bucket
  username: JzcIs0mOTKUDvWKJ1Dp3
  password: 0Y5GmgKrTs9MYSctrmsPdzFsKMZMpUwT04oCZLIu
rabbitmq:
  service_name: hello-world.rabbitmq-cluster.svc.cluster.local
  service_port: 5672
  queue_name: recognition-request
  username: default_user_waFUPHY_m019tVF5FlC
  password: J5RSzqB3jpZzIFtuFhenV7Nabw3Sb3g6
