#egyenlőre az image tagolása a lényeg -> a helm chart további részét majd kitöltjük a fejlesztéskor
env:
  #APP_VERSION egy string, amely a docker image tag-et fogja tartalmazni. A commit sha-t fogjuk erre használni.
  APP_VERSION: 5c553889780f2ef7094332055f2d22ad275d2547
#Minden, amit a webservice felhasznál a minio eléréséhez, itt van definiálva
minio:
  service_name: minio.minio.svc.cluster.local
  service_port: 9000
  bucket_name: ocr_bucket
  username: minioadmin
  password: minioadmin
