name: Pipeline

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}
  WEBSERVICE_IMAGE_NAME: "ocr-webservice"
  OCR_WATCHER_IMAGE_NAME: "ocr-watcher"
  OCR_WORKER_IMAGE_NAME: "ocr-worker"
  NOTIFICATION_IMAGE_NAME: "notification-service"

jobs:
    changes:
      runs-on: ubuntu-latest
      outputs:
        webservice: ${{ steps.filter.outputs.webservice }}
        ocr-watcher: ${{ steps.filter.outputs.ocr-watcher }}
        ocr-worker: ${{ steps.filter.outputs.ocr-worker }}
        notification: ${{ steps.filter.outputs.notification }}
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            webservice:
              - 'Webservice/!(helm/**)/**'
            ocr-watcher:
              - 'OCR_Service/Watcher/**'
            ocr-worker:
              - 'OCR_Service/Worker/**'
            notification:
              - 'Notification_service/!(helm/**)/**'



    lint-webservice:
        needs: changes
        if: ${{ needs.changes.outputs.webservice == 'true' }}
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Run golangci-lint
          uses: golangci/golangci-lint-action@v8
          with:
            working-directory: Webservice
    
    test-webservice:
        needs: changes
        if: ${{ needs.changes.outputs.webservice == 'true' }}
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Run tests
          run: | 
            cd Webservice
            go test ./...

    build-webservice:
        runs-on: ubuntu-latest
        needs: [lint-webservice, test-webservice, changes]
        if: ${{ needs.changes.outputs.webservice == 'true' }}
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ env.DOCKERHUB_USERNAME }}
            password: ${{ env.DOCKERHUB_KEY }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: ./Webservice
            push: true
            platforms: linux/arm64
            tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.WEBSERVICE_IMAGE_NAME }}:${{ github.sha }}
    
    lint-ocr-watcher:
        needs: changes
        if: ${{ needs.changes.outputs.ocr-watcher == 'true' }}
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Run golangci-lint
          uses: golangci/golangci-lint-action@v8
          with:
            working-directory: OCR_Service/Watcher
            version: latest
    
    test-ocr-watcher:
        needs: changes
        if: ${{ needs.changes.outputs.ocr-watcher == 'true' }}
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Run tests
          run: | 
            cd OCR_Service/Watcher
            go test ./...
    
    lint-ocr-worker:
        needs: changes
        if: ${{ needs.changes.outputs.ocr-worker == 'true' }}
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Install flake8
          run: pip install flake8
        - name: Run python lint
          working-directory: OCR_Service/Worker
          run: flake8 .
    
    test-ocr-worker:
        needs: changes
        if: ${{ needs.changes.outputs.ocr-worker == 'true' }}
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Install dependencies
          run: | 
            pip install pytest
            cd OCR_Service/Worker
            pytest
    
    build-ocr-watcher:
        runs-on: ubuntu-latest
        needs: [lint-ocr-watcher, test-ocr-watcher, changes]
        if: ${{ needs.changes.outputs.ocr-watcher == 'true' }}
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ env.DOCKERHUB_USERNAME }}
            password: ${{ env.DOCKERHUB_KEY }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Build and push watcher Docker image
          uses: docker/build-push-action@v4
          with:
            context: ./OCR_Service/Watcher
            push: true
            platforms: linux/arm64
            tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.OCR_WATCHER_IMAGE_NAME }}:${{ github.sha }}

    build-ocr-worker:
        runs-on: ubuntu-latest
        needs: [lint-ocr-worker, test-ocr-worker, changes]
        if: ${{ needs.changes.outputs.ocr-worker == 'true' }}
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ env.DOCKERHUB_USERNAME }}
            password: ${{ env.DOCKERHUB_KEY }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        
        - name: Build and push worker Docker image
          uses: docker/build-push-action@v4
          with:
            context: ./OCR_Service/Worker
            push: true
            platforms: linux/arm64
            tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.OCR_WORKER_IMAGE_NAME }}:${{ github.sha }}

    update-all-values:
        runs-on: ubuntu-latest
        needs: [build-ocr-watcher, build-ocr-worker, build-notification, build-webservice, changes]
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Update webservice values.yaml
          if: ${{ needs.changes.outputs.webservice == 'true' }}
          run: |
            cd Webservice/helm
            sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values.yaml 
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add values.yaml
        - name: Update OCR service values.yaml
          if: ${{ needs.changes.outputs.ocr-worker == 'true' || needs.changes.outputs.ocr-watcher == 'true'}}
          run: |
            cd OCR_Service/helm
            sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values.yaml 
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add values.yaml
        - name: Update Notification service values.yaml
          if:  ${{ needs.changes.outputs.notification == 'true' }}
          run: |
            cd Notification_Service/helm
            sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values.yaml 
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add values.yaml
        - name: Git commit and push all values.yaml changes
          run: |
            git commit -m "Update all values.yaml"
            git push
        

    lint-notification:
        needs: changes
        if: ${{ needs.changes.outputs.notification == 'true' }}
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Run golangci-lint
          uses: golangci/golangci-lint-action@v8
          with:
            working-directory: Notification_Service

    test-notification:
        needs: changes
        if: ${{ needs.changes.outputs.notification == 'true' }}
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Run tests
          run: | 
            cd Notification_Service
            go test ./...

    build-notification:
        runs-on: ubuntu-latest
        needs: [lint-notification, test-notification, changes]
        if: ${{ needs.changes.outputs.notification == 'true' }}
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ env.DOCKERHUB_USERNAME }}
            password: ${{ env.DOCKERHUB_KEY }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Build and push notification Docker image
          uses: docker/build-push-action@v4
          with:
            context: ./Notification_Service
            push: true
            platforms: linux/arm64
            tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.NOTIFICATION_IMAGE_NAME }}:${{ github.sha }}